name: sw

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: SoftwareNetwork/sw2
        path: sw
    - uses: ilammy/msvc-dev-cmd@v1
    - run: cl -nologo -std:c++latest -EHsc sw\src\main.cpp -link -OUT:sw.exe
    - run: .\sw.exe test
    
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      with:
        check_name: test (${{ matrix.os }})
        report_paths: .sw/test/results.xml
        github_token: ${{ secrets.GITHUB_TOKEN }}
    
  linux:
    runs-on: ubuntu-22.04
    container:
      image: fedora:37
      options: --security-opt seccomp=unconfined
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: SoftwareNetwork/sw2
        path: sw2
    - name: prepare
      run: |
        sudo dnf -y install gcc g++ fmt-devel
    - name: make_builder
      run: |
        g++ -std=c++2b sw2/src/*.cpp -o sw
    - name: run
      run: |
        ./sw test
        
