name: sw

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: SoftwareNetwork/sw4
        path: sw        
    - name: dir SYMLINK
      shell: cmd
      run: mklink /D runner/sw sw
    - uses: ilammy/msvc-dev-cmd@v1
    - run: cl -nologo -std:c++latest -EHsc runner/runner.cpp advapi32.lib ole32.lib OleAut32.lib -link -OUT:sw.exe
